version: '3.4'
services:
  docker-in-docker:
    restart: always
    privilaged: true
    image: goldentigerindia/docker-in-docker:0.0.0-c6038c2-dirty
    environment:
      - ENVIRONMENT_NAME=dev
      - BUILD_BRANCH=develop
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
